# Generated by Django 5.1.6 on 2025-10-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('agent', 'Corredor Inmobiliario'), ('buyer', 'Comprador')], default='buyer', max_length=10),
        ),
    ]
